export const ROLES = ["SUPER_ADMIN", "HR", "BDE", "TELESALES"];
export const EMPLOYEE_ROLES = ["BDE", "TELESALES"];
export const LEAD_STATUSES = ["NEW", "INTERESTED", "NOT_INTERESTED", "FOLLOW_UP", "PAYMENT_PENDING", "CONVERTED"];
export const TASK_STATUSES = ["PENDING", "IN_PROGRESS", "COMPLETED"];
export const NOTIFICATION_TYPES = ["INFO", "WARNING", "SUCCESS"];
